# Generated by Django 4.2.29 on 2026-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.URLField(blank=True, default='', verbose_name='URL de imagen'),
        ),
    ]
